### ISSUE TITLE
Update to the latest version of `ocrmypdf`

### ISSUE THREAD

**Issue by cmccambridge** [cmccambridge/ocrmypdf-auto#11]
Current image pins `ocrmypdf` at 6.2.0. Need to write more end-to-end regression tests and then upgrade to the latest (8.1.0 as of this issue).

**Comment by jo-me** [comment]
FYI, 
after upgrading everything to the latest version locally the result still worked.

 So, mainly chaging the base image to
`FROM ubuntu:20.10`

and upgrading the pip packages in requirements.txt to
```
plumbum==1.6.9
ocrmypdf==11.3.3
watchdog==0.10.3
requests~=2.25.0
```

ocrmypdf also has more dependencies that would be used if present, namely pngquant (via apt get) and jbig2 encoder (built during image creation).

**Comment by cmccambridge** [comment]
With thanks to @jo-me , this is now complete as of ocrmypdf 11.3.3.
