### ISSUE TITLE
Evaluate Alpine Linux base image

### ISSUE THREAD

**Issue by cmccambridge** [cmccambridge/ocrmypdf-auto#12]
Convert if possible, for size savings.

**Comment by jo-me** [comment]
I tried this out just for fun.

Without any optimizations to the general approach of this project (or the Dockerfile) an image based on alpine:3.12.1 saves me about 20% or 100MB using all the latest versions of the different components. 

![image](https://user-images.githubusercontent.com/10351272/99305555-3b2b7600-2854-11eb-8799-5c94a0646778.png)

If you're interested I can share the changes.

**Comment by cmccambridge** [comment]
Hey @jo-me ! Thanks **very** much for taking a look at this and for jumping in on these various issues to comment! I somehow have this repository misconfigured, and I am only receiving email alerts for direct replies to issues that I myself have opened, rather than alerts for all issues in the repository... It seems I have been missing new issues for a year now 🤦.

I'll take a look hopefully tonight, but certainly within the next few days, at updating the docker images here for a couple of these related topics: new Alpine version, latest & greatest ocrmypdf version, etc.

I'm not sure what questions I'll have for you just yet, but will keep you updated!

**Comment by cmccambridge** [comment]
(By the way if you've got any specific changes that you think are ready to just merge as a PR, feel free to put up a PR as well! Happy to take a look :) )

**Comment by jo-me** [comment]
I have created a PR for the package updates so that you don't have to go look them up again.
The change to the Dockerfile with the two phases is optional but useful if you want to include the jbig2 encoder. That thing has to be compiled so all the build tools are needed for that. You'll see :-)

**Comment by cmccambridge** [comment]
Thinking deeper here, I think there's more reward by taking your other suggestion: migrating to the official upstream docker container instead of rolling a new container just for ocrmypdf-auto.... so while Alpine does look promising on the image size, I think the benefit of no manual maintenance outweighs the reduction in image size, from my view.
