### ISSUE TITLE
Not starting processing of files

### ISSUE THREAD

**Issue by AlexZeller** [cmccambridge/ocrmypdf-auto#13]
I have the problem that I can't get any processing to happen. I set up the Container like in the Quick & Easy example. Everything seems to be fine and I get the Watching Folder notification. But if I copy a PDF in the input folder nothing happens. Any clue on why?

I tried different PDFs and checked if the volumes are mounted correctly. I did not use any custom config file.

**Comment by tedstriker** [comment]
Same here. This is from the log:

```
2019-04-28 11:12:48 - Processing: /input/tk.pdf -> /output/test.pdf
2019-04-28 11:12:52 - Processing complete in 4.410000 seconds with status 5: /input/test.pdf
TEST
```

What does status 5 mean?

**Comment by tedstriker** [comment]
the reason for me was a lack of read/write permissions in input and output directory. Got it fixed.

**Comment by AlexZeller** [comment]
It was the same for me. After changing the read write/permissions and the owner of the input and output folders inside the container it started processing. Thanks for the hint. Maybe this could be added to the documentary.
