### ISSUE TITLE
Fails when using OCRmyPDF options

### ISSUE THREAD

**Issue by Irish-link** [cmccambridge/ocrmypdf-auto#17]
The ocr.config file indicates that common OCRmyPDF options are allowed. No matter what options i add in or take out any time i use the "--redo-ocr" option it just hangs and does nothing. There is no CPU usage from the docker container and nothing happens. It just stays in the "input" folder. 

Any advice would be apreciated. Thanks!

**Comment by jo-me** [comment]
Did you set OCR_VERBOSITY to debug and check the logs?
It starts doing stuff on pdf files but in the logs you'll see that it detects changes in the input folder and what it does with each file.

**Comment by Irish-link** [comment]
Hey @jo-me thanks for checking in. Yeah, i actually just did that and its looking like I am getting a "ocrmypdf: error: unrecognized arguments: --redo-ocr" but based on the cookbook this is actually a part of OCRmyPDF. I tried their official one but the output of this -auto one is a much better looking output. 

Any chance this was created prior to the implementation of "--redo-ocr" i made an assumption that "--redo-ocr" was a part of it since "--force-ocr" worked when i tried it.

**Comment by jo-me** [comment]
This project uses a rather old version of ocrmypdf. Maybe redo-ocr was introduced in more recent versions.
I've upgraded the versions yesterday and used the redo-ocr param so it definitely works also in the context of ocrmypdf-auto.

Check out this commit (ignore the README file) : https://github.com/jo-me/ocrmypdf-auto/commit/67f9f1b86ffdef1e5555c5f8d80fc0a3a7a7a6e7
This is what I changed to create a (working) new docker image with the latest versions.

**Comment by Irish-link** [comment]
Sweet! Thanks a ton jo-me. I took a quick look and will try to implement tonight.

**Comment by cmccambridge** [comment]
@Irish-link Thanks to @jo-me 's help, this image is now updated with the latest ocrmypdf version, which supports the `--redo-ocr` flag. You should be able to pull the `latest` or `11.3.3` tags to update.

Please reopen if this doesn't sort out the errors you're seeing with `--redo-ocr`!
