### ISSUE TITLE
Feature: Implement auto-install of tesseract language packages

### ISSUE THREAD

**Issue by cmccambridge** [cmccambridge/ocrmypdf-auto#2]
Expose an `OCR_LANGUAGES` variable that can be used to instruct the container (in `docker-entrypoint.sh`, probably?) to install additional tesseract language packages.

Open question: Also add a default `-l <list>` option to `ocrmypdf` configuration?

**Comment by ChristianRiesen** [comment]
I'm interested in bringing this feature in. Let me see if I can find some time to add this. I could use some extra languages :)

**Comment by cmccambridge** [comment]
@ChristianRiesen That would be fantastic!

Here's one potential source of inspiration that I had seen in the past. (Granted, `paperless` is Alpine-based rather than this container's Ubuntu image, so it would need some adjustment): https://github.com/danielquinn/paperless/blob/master/scripts/docker-entrypoint.sh#L64

The current `Dockerfile` avoided dropping privileges in favor of letting the entrypoint do so at runtime via `gosu` with this potential need for some package management in mind, though if you have any different ideas or options there, I'd be very interested as well.

**Comment by ChristianRiesen** [comment]
I'll have a look. Please checkout the pull request I made too, I think that would be a great addition.

**Comment by ChristianRiesen** [comment]
There you go @cmccambridge 
Some work for you :)

**Comment by cmccambridge** [comment]
Excellent, thanks! Apologies that I could not get to the first PR last night - I'll be sure to this weekend :)

**Comment by ChristianRiesen** [comment]
No problem. Remember to adjust the template for both in unraid, I actually use it in that context. Thanks :)

**Comment by ChristianRiesen** [comment]
I guess this can be closed now :)

**Comment by cmccambridge** [comment]
Indeed! Took a few guess-and-check attempts to get the unraid template formatted in a way that unraid didn't mangle, but the unraid template is now up-to-date as well, and this issue is complete!
