### ISSUE TITLE
Feature Request: Setting resize / compression levels

### ISSUE THREAD

**Issue by Madd33n** [cmccambridge/ocrmypdf-auto#20]
As far as I can see:

- PDFs scanned at black/white or grayscale got a little 5-10% increased file size
My guess --> just because of the additional text layer - fine.

- PDFs scanned in color get a highly decreased file size - sometimes nearly 50% !
40-50% decrease is not possible without a high "loss" of information when compressing.

Can you provide such an option via the unRAID template to just set another parameter like 
CompressionLevel=veryhigh, high, normal, low, verylow, none

Additionally it would be nice to be able to set the output dpi. 
To get a optimal OCR the document should always scanned at a minimum of 300dpi. 
But there is no need to save the file after the recognition with 300dpi. Instead 200dpi is almost enough, decreasing the file size without any seeable quality losts. 

Thank you

**Comment by cmccambridge** [comment]
@Madd33n All image manipulation is done by the underlying `OCRmyPDF` program, and this program only provides a wrapper for ease of use on unraid.

Two ideas for you to try...
1. It's possible that the increase in size you are observing for color images may be related to deskewing the input images, which is enabled in the default configuration. Deskewing may rotate a page by only a few degrees and not be visually evident, yet cause a rerendering of all image content, and the output size increase you're seeing. To limit the processing to *only* adding the OCR text layer, you could try removing the `--deskew` option.
2. If you find that it is still necessary to compress the output images for your use case, you can control this through configuration options as well, e.g. `--jpeg-quality` or `--png-quality`. Can check the OCRmyPDF documentation for descriptions of these parameters, or to see if others might also help your use case.

Both of these settings are made not through the top-level variables on the unRAID template (there would be too many to list), but rather must be specified in a `ocr.config` file, which can be located in your config directory (e.g. `/mnt/user/appdata/ocrmypdf-auto`) or in your document input directory. See the documentation here for more information on how to configure OCR options: https://github.com/cmccambridge/ocrmypdf-auto#ocrmypdf-configuration-files

Let me know if that helps!

**Comment by Madd33n** [comment]
Thanks - I actually dont have a problem with the compression. But I saw some kind of optimization potential for your app :) 

But as you described it seems that's not worth to bring this settings to the unRAID template. 
I'll read the documentation of and - if I need/want - will change the settings directly in the config file.

Thanks for your feedback. Have a nice weekend and stay safe!

**Comment by cmccambridge** [comment]
Thanks @Madd33n!

Given the number of possible `ocrmypdf` options that _could_ be exposed as unRAID variables, I'm hesitant to add each one, as I could spend a long time trying to keep up with the changing list from upstream... From a few of the other issues on this wrapper project, I think it might be smarter time investment to move toward reusing more of the underlying `ocrmypdf` code instead of adding more to this wrapper.

That's the direction I'm planning to head at the moment, but I'm open to feedback :) 

I'll close this issue for now, but again - open to ideas or suggestions. Feel free to reopen this!
