### ISSUE TITLE
No output file - Status 5

### ISSUE THREAD

**Issue by asd913** [cmccambridge/ocrmypdf-auto#24]
2021-03-20 21:17:26 - Watching /input,
2021-03-20 21:17:56 - Processing: /input/HP scan -0046.pdf -> /output/HP scan -0046.pdf,
2021-03-20 21:18:01 - Processing complete in 4.140000 seconds with status 5: /input/HP scan -0046.pdf,
TESTOCR_PROCESS_RESULT/input/HP scan -0047.pdf/output/HP scan -0047.pdf54.020000

I installed this as a docker container and when a pdf is loaded into the input folder, the log gives me this output. No pdf is converted and placed in the output folder. 

What is status 5?

**Comment by asd913** [comment]
I figured it out. The issue is the output folder was automatically created when the container was made. I needed to set its permissions correctly.

**Comment by cmccambridge** [comment]
For future reference, the set of return codes per document job are defined by the upstream OCRmyPDF package that this container is wrapping. This set is documented for the current version here: https://ocrmypdf.readthedocs.io/en/latest/advanced.html#return-code-policy
