### ISSUE TITLE
Input files don't get recognized 

### ISSUE THREAD

**Issue by bennetrr** [cmccambridge/ocrmypdf-auto#26]
When I start the container and move files in the input folder, nothing happens. I don't even get any output in the logs.

Start command:
```bash
docker run \
  -v ./test-files/input/:/input \
  -v ./test-files/output/:/output \
  -v ./test-files/config/:/config \
  --env OCR_VERBOSITY=debug \
  --env OCR_LANGUAGES=deu \
  cmccambridge/ocrmypdf-auto
```

The config file `./test-files/config/ocr.config`:
[ocr.config](https://github.com/cmccambridge/ocrmypdf-auto/files/8717986/ocr.config.txt)

It also did not work with the example configuration.

The only thing in the logs beside the installation of the language pack is:
```
2022-05-18 15:58:45 [MainThread] - Watching /input
^C
2022-05-18 15:59:47 [MainThread] - Signal 2 (SIGINT) Received. Shutting down...
2022-05-18 15:59:47 [MainThread] - Shutting down filesystem watchdog...
2022-05-18 15:59:47 [MainThread] - Canceling all 0 in-flight tasks...
2022-05-18 15:59:47 [MainThread] - Shutting down threadpool...
2022-05-18 15:59:47 [MainThread] - Cleaning up filesystem watchdog...
```

I've tested the container on two systems:

Host OS: Ubuntu 21.04  //  Windows 1121H1 (22000.675)

Docker Version: 20.10.14 (a224086)  //  20.10.14 (a224086)

Docker Desktop Version: 4.8.1 (78998)  //  4.8.2 (79419) with WSL2 support

Both have the same issue. I think, on the first system the problem occurred after updating docker, but I don't know from which to which version and if I had Docker Desktop installed already. Maybe the issue is also related to Docker Desktop.

Do you have any idea why the container is not working? Thanks in advance

**Comment by cmccambridge** [comment]
@bennetrr best guess is that WSL2 (which your docker desktop engine perhaps recently migrated to?) doesn't properly trigger `inotify` for file change notifications.

Give it a try with `-e OCR_USE_POLLING_SCHEDULER=1` and see if that helps... If so, you can run that way at cost of a little CPU usage and latency, or you may need to try a bind mount from a WSL file system instead of a  shared windows one, for example.

**Comment by bennetrr** [comment]
Yes, the second system runs on WSL2, but the first system is running Ubuntu as host OS. So I don't think, that the issue is related to WSL2.

> Give it a try with `-e OCR_USE_POLLING_SCHEDULER=1`

I think I tried that already, but it didn't work either. I can try it tomorrow again, when I have enough time, and I can also try to get some other maschine and try it with a fresh install. I also wanted to try it with my Raspberry Pi, which has only Docker CLI installed, but it wouldn't work at all (maybe because of the architecture?)

The weird think is, that your container works perfectly on the Mac of my employer, who's also using Docker Desktop

**Comment by bennetrr** [comment]
I moved the files to the WSL2 file system and tried it again, and it works! I'm currently at school and have only my laptop here, but when I'm at home, i will try it with my main computer.

My theory is, that the new versions of Docker (or Docker Desktop?) don't trigger `inotify` when the mounted volume is on a file system that is not the system partition.

**Comment by bennetrr** [comment]
I have now tried to start the container with the volumes on the system partition, but it still does not work. On my laptop it works perfect though. I think, my PC is just broken :smile:. However, i will continue working on my laptop until I reinstall my pc.

Thanks for your help!
