### ISSUE TITLE
Feature: Experiment with building tesseract v4 on Alpine Linux

### ISSUE THREAD

**Issue by cmccambridge** [cmccambridge/ocrmypdf-auto#3]
Not sure how much size savings could be realized by switching to Alpine, given how many other packages get pulled in to satisfy `ocrmypdf` dependencies and _their_ dependencies, but the biggest obstacle up front is that the only `tesseract-ocr` available for Alpine seems to be v3.05, which is considerably poorer performing than the not-yet-release v4 code.

**Comment by cmccambridge** [comment]
This has now been done, at least in alpine `edge`, following official release of tesseract 4.0!

**Comment by jo-me** [comment]
4.1.1 is available in edge and releases 
https://pkgs.alpinelinux.org/packages?name=tesseract-ocr&branch=v3.12
