### ISSUE TITLE
OCR_NOTIFY_URL for MS Teams Webhook

### ISSUE THREAD

**Issue by it-balaskas** [cmccambridge/ocrmypdf-auto#30]
I'd like someone to help me set my webhook url, i've been reading 
https://ocrmypdf.readthedocs.io/en/v9.7.1/api.html
without success..

Working configuration over portainer on a machine with physical resources.
Thank you in advance!

**Comment by cmccambridge** [comment]
Hi @it-balaskas 

Unfortunately this project - `ocrmypdf-auto` has met my personal needs for some time and I am not doing any active development, maintenance, or support work on it. As a result, it has drifted significantly far behind the upstream `ocrmypdf` project, which is on major release 15.3.

I would encourage you to take a look at the upstream project's support for [Hot/Watched folders](https://ocrmypdf.readthedocs.io/en/latest/batch.html#hot-watched-folders) and adapt it to your needs.

Or, always welcome to fork this code and modify it to better suit your needs, e.g. if MS Teams needs something specific in its webhook beyond the basic `OCR_NOTIFY_URL` that was added to this script years ago.
